### ISSUE TITLE
Kubernetes example

### ISSUE THREAD

**Issue by AudriusButkevicius** [AdamColton/genericusecases#1]
While reading comments in https://news.ycombinator.com/item?id=14803510
Someone pointed out https://github.com/kubernetes/kubernetes/tree/master/cmd/libs/go2idl/client-gen/generators which is apparently code generation tools written pretty much because of lack of generics.

Haven't dug into it, but it seems relevant.

**Comment by AdamColton** [comment]
Thanks. I added it to the document.
